### ISSUE TITLE
[July 16, 2023] Scrum Update 

### ISSUE THREAD

**Issue by ajo01** [kylexrich/coursegpt#113]
Describe (for the project):

1. what you’ve worked on in the previous two weeks,
2. what you’ll be working on in the next two weeks,
3. where you might have gotten stuck during the last two weeks.

Total: ~5 sentences max!

**Comment by ajo01** [comment]
Name: Amy Jo (k4y2b)

1. what you’ve worked on in the previous two weeks,
- making the website responsive #110 and minor feedback UI improvements #111 
2. what you’ll be working on in the next two weeks,
- I'll likely work on the data analytics visualization and improving the profiles modal UI
3. where you might have gotten stuck during the last two weeks.
- I initially looked into code formatting in the bot answers but due to already using a third party library in the chat section, integration looks difficult and was dropped

**Comment by huangcar1** [comment]
Name: Carolyn Huang (m5y3w)

1. what you’ve worked on in the previous two weeks
I've been working on data analytics for question and answer pairs (see [this issue](https://github.com/kylexrich/coursegpt/issues/57))

2. what you’ll be working on in the next two weeks,
Continuing work on this ticket; bettering the front end of the page and figuring out why the model isn't working

3. where you might have gotten stuck during the last two weeks.
The model currently isn't working :( using a 3rd party library and having troubles finding out how to integrate this. Will be working in this super in depth in the coming weekend, though

**Comment by kylexrich** [comment]
Kyle Rich h7w2b

1. What did you work on this past iteration (4 weeks)?
- **Finished on-demand course training** so that professors can train their courses with whatever data they prefer.
  - https://github.com/kylexrich/coursegpt/issues/103
  - https://github.com/kylexrich/coursegpt/issues/61
  - https://github.com/kylexrich/coursegpt/issues/72
  - https://github.com/kylexrich/coursegpt/issues/74
- [Changed the Username on the UI to be the user's actual name](https://github.com/kylexrich/coursegpt/issues/101)
- [Implemented auto-generated titles for each chat](https://github.com/kylexrich/coursegpt/issues/98)
- Fixed various bugs / made user interaction improvements
  - https://github.com/kylexrich/coursegpt/issues/97
  - https://github.com/kylexrich/coursegpt/issues/95
  - https://github.com/kylexrich/coursegpt/issues/94
  - https://github.com/kylexrich/coursegpt/issues/73
- [Started working on improving the CourseGPT model's ability to answer questions according to the available data](https://github.com/kylexrich/coursegpt/issues/105)
- [Started training the CourseGPT model on more data relevant to CPSC 455. Successfully trained it on a 500 page pdf yesterday! Super excited.](https://github.com/kylexrich/coursegpt/issues/109)

2. What were any major issues/challenges you ran into?
Honestly the biggest challenge I faced was the architectural design relating to the on-demand course training. There were various approaches that I could have taken, all with their own pro's and con's with respect to software design principles, design patterns, latency, flexibility, etc. After white-boarding for a while, I finally decided on an approach I was happy with.

3. What do you plan to work on for this coming iteration (2 weeks)?
- Make the CourseGPT model 300% perfect, with all of the data it needs for the final demo.
- Implement better error handling, possibly throttling/rate limiting, for when professors need to train chat gpt on large amounts of data
- Do input validation for security

**Comment by duffydu** [comment]
Name: Duffy Du (f4r3h)

1. what you’ve worked on in the previous two weeks,
- I mainly worked on adding a new user registration form where users can choose their account type, school and courses before going to the main chat page. This PR is successfully merged, see [!107](https://github.com/kylexrich/coursegpt/pull/107)
- I have spent time on manual testing our dev branch and have caught some bugs that are under investigation at the moment.
- I have also gotten started working on a chat search bar.

2. what you’ll be working on in the next two weeks,
- I will continue to work on the chat search bar functionality
- Debugging the bugs found through manual testing
- Doing more manual testing and working towards perfecting our final product

3. where you might have gotten stuck during the last two weeks.
I had a little difficulty using the custom react hooks for checkboxes and radio buttons in Chakra UI, but I was able to figure out the problems through searching and trial and error.

**Comment by ritikk7** [comment]
Name: Ritik Keswani (l6v5i)

1. what you’ve worked on in the previous two weeks
profile settings modal enhancement, adding image upload functionality, and adding password change functionality.  

2. what you’ll be working on in the next two weeks,
Continuing work on this ticket; bettering the front end of the page and adding copy to clipboard functionality.

3. where you might have gotten stuck during the last two weeks.
figuring out a way to persist images since they take up a lot of memory so MongoDB wouldn't be enough.
