### ISSUE TITLE
[June 25, 2023] Scrum Update 

### ISSUE THREAD

**Issue by ajo01** [kylexrich/coursegpt#89]
Describe (for the project):

1. what you’ve worked on in the previous two weeks,
2. what you’ll be working on in the next two weeks,
3. where you might have gotten stuck during the last two weeks.

(~1 sentence per three items; expand on at least 1 item for full participation marks)

**Comment by ajo01** [comment]
Name: Amy Jo (k4y2b)

1. what you’ve worked on in the previous two weeks

- message/chat controller #49, chat history #64, chat dropdown filter by course #71, individual chat deletion #83, typewriter animation #84, etc

2. what you’ll be working on in the next two weeks,
- do code formatting in bot answers and potentially make the website responsive + various polish tasks

3. where you might have gotten stuck during the last two weeks.
- there were no blockers the past sprint, since it was mostly frontend features which I'm familiar with

**Comment by huangcar1** [comment]
Name: Carolyn Huang (m5y3w)

- What I've worked on: [feedback frontend and backend](https://github.com/kylexrich/coursegpt/pull/78) and some refactoring changes

**Comment by duffydu** [comment]
Name: Duffy Du (f4r3h)

1. what you’ve worked on in the previous two weeks
- I mainly worked on translating the jupyter notebook model prototype to javascript code, and getting a courseGPT response from the CPSC455 model working end to end. [!76](https://github.com/kylexrich/coursegpt/pull/76)
2. what you’ll be working on in the next two weeks,
- Doing some polishing and clean up tasks [!65](https://github.com/kylexrich/coursegpt/issues/65)
- Implementing a chat search functionality [!63](https://github.com/kylexrich/coursegpt/issues/63)
3. where you might have gotten stuck during the last two weeks.
- Gotten stuck on finding equivalent javascript packages for the python libraries used in the initial code querying the model which was written in python. But was able to try different packages and eventually got it working.

**Comment by kylexrich** [comment]
Kyle Rich h7w2b

1. What did you work on this past iteration (2 weeks)?
- [Finished redux and selector implementation](https://github.com/kylexrich/coursegpt/tree/refactoring)
- [Almost finished on-demand course training](https://github.com/kylexrich/coursegpt/issues/17) so that professors can train their courses with whatever data they prefer.
- [Improved the user flow for chat creation and sending messages](https://github.com/kylexrich/coursegpt/issues/82)
- [Fixed some chat creation bugs](https://github.com/kylexrich/coursegpt/issues/90)
- [Enhanced the chat ui to include a loading state while users wait for their gpt response](https://github.com/kylexrich/coursegpt/issues/73)
- [Delete chat history functionality](https://github.com/kylexrich/coursegpt/issues/29)

2. What were any major issues/challenges you ran into?
The biggest challenge was, by far, implementing the on-demand course training mentioned above. Its still a work in progress, but figuring out the most optimal method to store and read data has been a struggle. Lots of learning!

3. What do you plan to work on for this coming iteration (2 weeks)?
- Finish on-demand course training, front to back.
- Likely create a separate interface for professor users

**Comment by ritikk7** [comment]
Name: Ritik Keswani (l6v5i)

1. What did you work on this past iteration (2 weeks)?
-> Minor UI enhancements and started work on the revamp of the profile page

2. What were any major issues/challenges you ran into?
-> Getting MongoDB to work on my computer since it was being blocked by Window's security workflows.

3. What do you plan to work on for this coming iteration (2 weeks)?
-> Completing the profile page revamp and making any enhancements as necessary.
